language: node_js
node_js:
  - "8"
cache: yarn
install: yarn install
script: yarn build
deploy:
  provider: pages
  local_dir: "./build"
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  on:
    branch: travis